create table barcode
(
    id     bigint generated by default as identity,
    "code" varchar(20) not null,
    sku_id bigint      not null,
    primary key (id)
);

create table center
(
    id       bigint generated by default as identity,
    "code"   varchar(20) not null,
    "name"   varchar(20) not null,
    "status" varchar(20) not null,
    primary key (id)
);

create table sku
(
    id       bigint generated by default as identity,
    "code"   varchar(20) not null,
    "name"   varchar(20) not null,
    "status" varchar(20) not null,
    primary key (id)
);
